#!/usr/bin/env python3

from datetime import datetime
from subprocess import call
import os
import sys
from sys import exit
import configparser

try:
	import requests
except ImportError:
	print("Could not import a required module - is python-requests installed?")
	exit()

def readConfig():
	path = sys.path[0]
	config = configparser.ConfigParser()
	config.read(path+'/slopy.cfg')
	image_dir = config.get('config', 'image_dir')
	image_format = config.get('config', 'image_format')
	date_format = config.get('config', 'date_format')
	return (image_dir, image_format, date_format)

def readHost():
	path = sys.path[0]
	config = configparser.ConfigParser()
	config.read(path+'/slopy.cfg')
	image_host = config.get('config', 'image_host')
	config.read(path+'/hosts.cfg')
	post_url = config.get(image_host, 'post_url')
	link_url = config.get(image_host, 'link_url')
	payload_format = config.get(image_host, 'payload_format')
	split_point = int(config.get(image_host, 'split_point'))
	return(post_url, link_url, payload_format, split_point)

def getImage():
	image_dir, image_format, date_format = readConfig()
	date_stamp = (datetime.now().strftime(date_format)+(image_format))
	file_uri = image_dir+date_stamp 
	call(["maim", "-s", file_uri])

	return (file_uri)


def main():	
	upload = getImage()
	post_url, link_url, payload_format, split_point = readHost()
	print (payload_format)
	try:
		response = requests.post(
			url=post_url,
			files={payload_format:open(upload, "rb")}
		)
	except Exception as e:
		print("Error uploading {0}".format(e))
		exit()

	local = upload.split('/')
	local = (local[-1] if len(local) > 1 else local[0])
	print(response.text)
	remote = link_url + response.text.split('"')[split_point]

	sys.stdout.write(remote)
	sys.exit()

#	print(local + " -> " + remote)
#	print("copied to clipboard maybe??")

if __name__ == '__main__':
	main()
